#!/usr/bin/env python3
"""Tests for agent_dev: the verbs, how they bind a tool's profile to the policy file, and the refusals."""

import contextlib
import io
import json
import pathlib
import tempfile
import unittest

import agent_dev as cli
import agent_dev_config as c
import agent_dev_profiles as p

SOME_SUBNET = "172.30.0.0/16"
SOME_DOMAIN = "api.anthropic.com"
SOME_EXTRA_DOMAIN = "extra.example.com"
SOME_GATEWAY = "host.docker.internal"
UNKNOWN_TOOL = "nonesuch"
BASIC_POLICY = f'[egress]\nallow = ["{SOME_DOMAIN}"]\n'
EMPTY_ALLOW_POLICY = "[egress]\nallow = []\n"
OW_POLICY = (
    BASIC_POLICY
    + '[open-weight]\npeer = "host"\n[open-weight.models]\n"claude-opus-5-5" = "glm-5.3:cloud"\n'
)
BAD_TOML = "this is = = not toml"


def run_cli(*argv: str) -> tuple[int, str, str]:
    """Run one verb in process, returning its status, stdout and stderr."""
    out, err = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        status = cli.main(list(argv))
    return status, out.getvalue(), err.getvalue()


class VerbTests(unittest.TestCase):
    def setUp(self):
        self._dir = tempfile.TemporaryDirectory()
        self.addCleanup(self._dir.cleanup)
        self.dir = pathlib.Path(self._dir.name)

    def config(self, text: str) -> str:
        path = self.dir / "policy.toml"
        path.write_text(text)
        return str(path)

    def claude(self, *argv: str) -> tuple[int, str, str]:
        return run_cli("--tool", "claude", *argv)


class Profile(VerbTests):
    def test_the_profile_verb_prints_the_shell_view_and_needs_no_config(self):
        status, out, _ = self.claude("profile")
        self.assertEqual(status, 0)
        self.assertEqual(out, p.shell_profile(p.CLAUDE))


class SessionSettings(VerbTests):
    def test_the_verb_prints_the_profiles_document(self):
        status, out, _ = self.claude("session-settings", self.config(BASIC_POLICY))
        self.assertEqual(status, 0)
        self.assertEqual(json.loads(out), p.SANDBOX_OFF)

    def test_ow_without_a_table_is_refused_with_the_commands_name(self):
        status, out, err = self.claude(
            "session-settings", self.config(BASIC_POLICY), "--ow"
        )
        self.assertEqual(status, 1)
        self.assertEqual(out, "")
        self.assertTrue(err.startswith(f"{p.CLAUDE.command}: "), err)


class SquidConf(VerbTests):
    def conf(self, policy: str, *extra: str) -> tuple[int, str, str]:
        return self.claude(
            "squid-conf", self.config(policy), "--subnet", SOME_SUBNET, *extra
        )

    def test_the_proxy_is_named_for_the_command_by_default(self):
        _, out, _ = self.conf(BASIC_POLICY)
        self.assertIn(f"visible_hostname {p.CLAUDE.command}-proxy", out)
        self.assertIn(f"# generated by {p.CLAUDE.command} for {p.CLAUDE.command}", out)
        self.assertIn(f'"/etc/{p.CLAUDE.command}/allowlist.txt"', out)

    def test_an_explicit_label_names_the_session(self):
        _, out, _ = self.conf(BASIC_POLICY, "--label", "claude-dev-7-8")
        self.assertIn("for claude-dev-7-8", out)

    def test_an_empty_allow_list_names_the_profiles_mandatory_host(self):
        status, _, err = self.conf(EMPTY_ALLOW_POLICY)
        self.assertEqual(status, 1)
        self.assertIn(p.CLAUDE.mandatory_host, err)

    def test_the_reverse_port_admits_the_profiles_path_shape(self):
        status, out, err = self.conf(OW_POLICY, "--ow", "--host-gateway", SOME_GATEWAY)
        self.assertEqual(status, 0, err)
        self.assertIn(
            f"acl ow_paths urlpath_regex {p.CLAUDE.inference_path_regex}", out
        )

    def test_the_per_run_allow_entries_reach_the_allow_list_verb_last(self):
        status, out, _ = self.claude(
            "allowlist", self.config(BASIC_POLICY), "--allow", SOME_EXTRA_DOMAIN
        )
        self.assertEqual(status, 0)
        self.assertEqual(out.splitlines(), [SOME_DOMAIN, SOME_EXTRA_DOMAIN])


class Refusals(VerbTests):
    def test_an_unknown_tool_is_refused_before_anything_is_read(self):
        status, out, err = run_cli("--tool", UNKNOWN_TOOL, "profile")
        self.assertEqual(status, 1)
        self.assertEqual(out, "")
        self.assertTrue(err.startswith("agent-dev: "), err)
        self.assertIn(UNKNOWN_TOOL, err)

    def test_a_config_that_will_not_parse_is_refused_naming_the_file(self):
        path = self.config(BAD_TOML)
        status, _, err = self.claude("settings", path)
        self.assertEqual(status, 1)
        self.assertIn(path, err)

    def test_the_settings_verb_is_the_engines_shell_view(self):
        status, out, _ = self.claude("settings", self.config(BASIC_POLICY))
        self.assertEqual(status, 0)
        self.assertIn(f"PROXY_PORT={c.PROXY_PORT}", out.splitlines())


if __name__ == "__main__":
    unittest.main()
